name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  pre-release:
    name: "Pre Release"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          
      - name: "Install CMake"
        if: matrix.os == 'windows-latest'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: "Run CMake"
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: "Run Makefile"
        if: matrix.os != 'windows-latest'
        run: make

      - name: "Build project"
        if: matrix.os == 'windows-latest'
        run: cmake --build build
        
      - name: "Release | Upload artifacts (Windows)"
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: battleship-${{ matrix.os }}.exe
          path: build\Debug\battleship.exe
          
      - name: "Release | Upload artifacts (Other)"
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: battleship-${{ matrix.os }}
          path: build/battleship
          
  upload_artifacts:
    name: Add Build Artifacts to Release
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Artifacts
        uses: actions/download-artifact@v3

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            battleship-ubuntu-latest/battleship-ubuntu-latest
            battleship-windows-latest.exe/battleship-windows-latest.exe
