name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  pre-release:
    name: "Pre Release"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          
      - name: "Run Makefile"
        run: make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            if [ "$RUNNER_OS" == "Windows" ]; then
              build\battleship
            else
              build/battleship
            fi
