name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: battleship-linux
          - os: windows-latest
            name: battleship-windows.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: "Build Project (Windows)"
        if: matrix.os == 'windows-latest'
        run: |
          cmake -DPROGRAM_VERSION="${{ github.ref_name }}" -G Ninja -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build -- -j 2
          mv build\battleship.exe ${{ matrix.name }}

      - name: "Build Project (Linux/macOS)"
        if: matrix.os != 'windows-latest'
        run: |
          make PROGRAM_VERSION=${{ github.ref_name }} release
          mv build/battleship ${{ matrix.name }}

      - name: "Calculate SHA-256 sum"
        id: hash
        run:
          openssl dgst -sha256 -r ${{ matrix.name }} | awk '{print $1}' > "${{ matrix.name }}.sha256"

      - name: "Release | Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: battleship
          path: |
            ${{ matrix.name }}.sha256
            ${{ matrix.name }}

  build-server:
    name: Build Server (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Build Server"
        run: |
          make server
          mv build/server battleship-server-linux

      - name: "Calculate SHA-256 sum"
        id: hash
        run:
          openssl dgst -sha256 -r battleship-server-linux | awk '{print $1}' > "battleship-server-linux.sha256"

      - name: "Release | Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: battleship
          path: |
            battleship-server-linux.sha256
            battleship-server-linux

  upload_artifacts:
    name: Add Build Artifacts to Release
    needs:
      - tagged-release
      - build-server
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Artifacts
        uses: actions/download-artifact@v3

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: battleship/battleship*
