name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release_test:
    name: Release Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          make

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: >-
          make release;
          find test/ -name "*.txt" -exec bash -c 'echo "Testing $1"; build/battleship -f "$1" 1> /dev/null; echo "Test $1 passed"' _ {} \;