name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release_test:
    name: Release Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          make

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: >-
          make release
          
          # Test the project
          for i in $(find test/ -name "*.txt") 
          do
            echo "Testing $i"
            build/battleship -f $i >> /dev/null
            echo "Test $i passed\n"
          done