name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release_test:
    name: Release Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: |
          make

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: |
          make release
          
          # Test the project
          build/battleship format0.txt
          build/battleship format1.txt
          build/battleship format2.txt
          build/battleship format3.txt
          build/battleship format4.txt
          build/battleship format5.txt