name: make

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Report test-coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          # Install the CLI
          curl https://deepsource.io/cli | sh
          
          lcov --directory src --capture --output-file coverage.info

          # Send the report to DeepSource
          ./bin/deepsource report --analyzer test-coverage --key cxx --value-file ./coverage.info
      
